const PHRASE = [
  "This is a random phrase",
  "Ahri > Karma",
  "The Waifu meta is broken",
  "The quick brown fox jumps over the lazy dog",
  "Esta es una frase aleatoria",
  "Idk put here something random",
  "I am a random phrase",
  "I have 600k mastery point with Ahri in LOL",
  "Это случайная фраза",
  "This is a very very very very very so much long random phrase",
  "This is the version 1.0.0 of the random phrases",
  "This is the version 5 of my portfolio",
  "The theme of the portfolio is me favorite character(Ahri, Hu Tao not)",
  "I learned a lot of things in this portfolio",
  "I learning english, and I have a lot of fun",
  "My english is B2, thanks documentation in english",
  "Esta es otra frase aleatoria",
  "Never mind the fact that I am a random phrase",
  "The first version of me porftolio was created in early 2019",
  "I am Front-end developer",
  "My first project was a rpg game",
  "I play LOL since 2020 but I know Ahri since 2017 without knowing what she was LOL!!!",
  "This is the phrase number 22",
  "This is the phrase number 23",
  "This is the phrase number 24",
  "This is the phrase number 25",
  "This is not a good idea",
  "Well... Are you hungry?",
  "DXDXDXDXD esarhp modnar a si shiT",
  "My favorite food is the fried chicken!!!",
  "I am a Ahri lover ;_)",
  "Well.. this ia a good Idea",
  "I dont have idea, but I will try",
  "in 2023 will there be a 3D portfolio??? ,:)",
  "I need a new chair",
  "404 not found",
  "Road to start a new project",
  "Try wrapping letters in your projects too!",
  "Wrapping letters in your projects is a good idea",
  "Wrapping Letters is a good idea",
  "Wrapping Letters need a upgrade now!!!",
  "When will my new portfolio be ready?",
  "fklnekjfna;kjfn;ansef  ahfkjhnajklsnefjknajsn ij;kfdjaklsjdfk;f afk m;ajef",
  "Índice de frases aleatorias",
  "¡¡¡La batalla ya a empezado, en un mundo muy cuadrado!!!",
  "Does anyone read this...?",
  "Chiken, french fries, reChiken, tomate, and a lot of other things...",
  "Well, I am a random phrase",
  "Tip, if you want read more random phrase, refresh the page Xd",
  "Whith sugar please",
  "Whithout sugar please",
  "POV: You read a random phrase...",
  "I am a string",
  "01110101 01110111 01110101",
  "You know what? I am a random phrase",
  "You know what? I am a Hacker )w(",
  "I am a front-end developer for accident...",
  "My first languaje code is C# !!!, but I dont remember how to use it Xd",
  "Una parte de esta frases fueron evaluadas por el traductor de google, tienen un sello de garantia Xd",
  "I am a random phrase",
  "I started learn JS with a manual of 1998",
  "I am from a random country",
  "without idea for more random phrases",
  "I kidding, I have so much random phrases!!!",
  "I waiting for the remake of Ahri",
  "this is a lowercase phrase",
  "I want a Baleada",
  "Are you can buy me a M1 Max? :D",
  "",
  "Later put more random phrases",
  'A phrase is "" Xd',
  "Are the sentences repeated a lot?",
];

// get random phrase
export const getRandomPhrase = () => {
  const random = Math.floor(Math.random() * PHRASE.length);
  return PHRASE[random];
};
